3 js
TihomirovPro/purpleSchool pull request #4
Opened 2023-09-29 17:02 UTC by TihomirovPro

2023-09-30 06:16 UTC, korbutds commented on 10-array-clean/index.js
> +  }
`for..in` - [лучше не использовать для итерации по массивам](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/for...in#%D0%BF%D1%80%D0%BE%D1%85%D0%BE%D0%B4_%D0%BF%D0%BE_%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%83_%D0%B8_for...in). Попробуйте через `for..of`.

2023-09-30 07:01 UTC, korbutds commented on 11-date-array/index.js
Не все так просто. Тут нужно чуть-чуть подумать. Задание то в следующем:
1. Валидные даты в 2х форматах - ДД-ММ-ГГГГ и ММ/ДД/ГГГГ
2. Все даты нужно привести к одному формату - ДД-ММ-ГГГГ
3. Потом нужно провести их валидацию. 31-04-2023 - дата невалидная

2023-10-02 13:54 UTC, Levitinn requested changes
Молодец, подправь пару моментов и можно будет принять

2023-10-02 13:54 UTC, Levitinn commented on 11-date-array/index.js
> +      ) { return true }
в таким случаях, не обязательно указывать return true/ return false.
Если элемент удовлетворяет описанному твоему условию, можешь написать 
`const filterArr = arr
    .filter(el => {
      if (
        el.length === 10 &&
        (el[2] === '-' || el[2] === '/') &&
        (el[5] === '-' || el[5] === '/')
      ) { return el }
    })`
это позволит сделать код чище

2023-10-02 13:54 UTC, Levitinn commented on 12-luna/index.js
> +    .filter(el => typeof el === 'number' && !isNaN(el));
очень длинная цепочка методов получилась.
кажется, можно избавиться от последнего (фильтр) и перенести его логику в map

2023-10-02 13:54 UTC, Levitinn commented on 10-array-clean/index.js
> +}
`function isRemove (num) {
  num > 5 ? true : false
}`

2023-10-02 14:56 UTC, Levitinn approved these changes

2023-10-02 14:56 UTC, Levitinn commented on 12-luna/index.js
> +  const card = string.split('').filter(el => !isNaN(el));
отлично

2023-10-02 15:55 UTC, merged